config/routes.rb
Rails.application.routes.draw do
  root to: "artists#index"

  resources :artists do
    resources :songs
  end

  get     "/artists_az"  => "artists#index_az", as: :artists_az
  get     "/artists_za"  => "artists#index_za", as: :artists_za
  get     "/artists_created_asc" => "artists#index_created_asc", as: :artists_created_asc
  get     "/artists_created_desc" => "artists#index_created_desc", as: :artists_created_desc


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_one :photo, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :bio, length: { maximum: 1000 }

  def self.order_by_name
    order :name
  end

  def self.order_by_name_desc
    order name: :desc
  end

  def self.order_by_created_at
    order :created_at
  end

  def self.order_by_created_at_desc
    order created_at: :desc
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: { maximum: 100 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def index_az
    @artists = Artist.order_by_name
  end

  def index_za
    @artists = Artist.order_by_name_desc
  end

  def index_created_asc
    @artists = Artist.order_by_created_at
  end

  def index_created_desc
    @artists = Artist.order_by_created_at_desc
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)

    if @artist.save
        @artist.photo.create(image_params)
        redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to root_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :bio)
  end

  def image_params
    params.require[:photo].permit(:image)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @artist = Artist.find(params[:artist_id])
    @songs = @artist.songs
    @song_ids = @songs.ids
  end

  def show
    @song = Song.find(params[:artist_id, :id])
  end

  def new
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    song = @artist.songs.new(song_params)

    if song.save
       render status: :created, json: song
    else
       render status: 402, json:  {
       errors: song.errors
     }.to_json
    end
end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
  end

  private

  def song_params
    params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
</div>

<label>Photos</label>
<div class="form-group">
  <span class="btn btn-default">
    Upload Photo
    <%= file_field_tag "image", type: :file, multiple: false %>
  </span>
</div>
<div>
  <%= f.submit "Save" %>

</div>
<% end %>

app/views/artists/index.html.erb
<div class='container-fluid'>
<h1>Artists</h1>


<% @artists.each do |artist| %>
<%= link_to artist_songs_path(artist) do %>
<div class="img-outline">
<div style="background:url(<%= artist.photo.image %>)no-repeat center center;background-size:cover;" class="round-img"><p class="artist_name"><%= artist.name %></p></div>
</div>
<% end %>
<% end %>
</div>

<%= link_to artists_created_asc_path do %>
<div class="btn btn-primary top-btn">
  Sort by Newest
</div>
<% end %>

<%= link_to artists_az_path do %>
<div class="btn btn-primary top-right-btn">
  Sort A-Z
</div>
<% end %>

app/views/artists/index_az.html.erb
<div class='container-fluid'>
<h1>Artists</h1>


<% @artists.each do |artist| %>
<%= link_to artist_songs_path(artist) do %>
<div class="img-outline">
<div style="background:url(<%= artist.photo.image %>)no-repeat center center;background-size:cover;" class="round-img"><p class="artist_name"><%= artist.name %></p></div>
</div>
<% end %>
<% end %>
</div>

<%= link_to artists_created_asc_path do %>
<div class="btn btn-primary top-btn">
  Sort by Newest
</div>
<% end %>

<%= link_to artists_za_path do %>
<div class="btn btn-primary top-right-btn">
  Sort Z-A
</div>
<% end %>

app/views/artists/index_created_asc.html.erb
<div class='container-fluid'>
<h1>Artists</h1>


<% @artists.each do |artist| %>
<%= link_to artist_songs_path(artist) do %>
<div class="img-outline">
<div style="background:url(<%= artist.photo.image %>)no-repeat center center;background-size:cover;" class="round-img"><p class="artist_name"><%= artist.name %></p></div>
</div>
<% end %>
<% end %>
</div>

<%= link_to artists_created_desc_path do %>
<div class="btn btn-primary top-btn">
  Sort by Oldest
</div>
<% end %>

<%= link_to artists_az_path do %>
<div class="btn btn-primary top-right-btn">
  Sort A-Z
</div>
<% end %>

app/views/artists/index_created_desc.html.erb
<div class='container-fluid'>
<h1>Artists</h1>


<% @artists.each do |artist| %>
<%= link_to artist_songs_path(artist) do %>
<div class="img-outline">
<div style="background:url(<%= artist.photo.image %>)no-repeat center center;background-size:cover;" class="round-img"><p class="artist_name"><%= artist.name %></p></div>
</div>
<% end %>
<% end %>
</div>

<%= link_to artists_created_asc_path do %>
<div class="btn btn-primary top-btn">
  Sort by Newest
</div>
<% end %>

<%= link_to artists_az_path do %>
<div class="btn btn-primary top-right-btn">
  Sort A-Z
</div>
<% end %>

app/views/artists/index_za.html.erb
<div class='container-fluid'>
<h1>Artists</h1>


<% @artists.each do |artist| %>
<%= link_to artist_songs_path(artist) do %>
<div class="img-outline">
<div style="background:url(<%= artist.photo.image %>)no-repeat center center;background-size:cover;" class="round-img"><p class="artist_name"><%= artist.name %></p></div>
</div>
<% end %>
<% end %>
</div>

<%= link_to artists_created_asc_path do %>
<div class="btn btn-primary top-btn">
  Sort by Newest
</div>
<% end %>

<%= link_to artists_az_path do %>
<div class="btn btn-primary top-right-btn">
  Sort A-Z
</div>
<% end %>

app/views/artists/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Russo+One|Julius+Sans+One|Jaldi" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <%= link_to root_path do %>
    <div class="navbar-header">
      <a class="navbar-brand">CODAISSEURIFY</a>
    </div>
    <% end %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Artists", root_path %></li>
    </ul>
  </div>
</nav>

app/views/songs/_song_form.html.erb
<%= form_for [@artist, @artist.songs.new], :class => "new_song" do |f| %>

<div>

  <%= f.text_field :name, placeholder: "Type Here", :class => "text_field" %>
</div>
<div>
  <%= f.submit "Add Song", :class => "submit" %>

</div>
<% end %>

app/views/songs/index.html.erb
<div class=container-fluid>
<%= image_tag @artist.photo.image, class: "artist-img" %>

<div class="whitebox">
<h1 class="align-left"><%= @artist.name %></h1>

<p class="align-left"><%= @artist.bio %></p>

  <%= link_to artist_path(@artist), method: :delete, data: { confirm: "Are you sure?" } do %>
  <h3 class="btn btn-primary top-right-btn"><i class="fa fa-minus-circle" aria-hidden="true"></i> Delete Artist</h3>
  <% end %>

  <div id="delete-songs" onclick="deleteAllSongs()" class="btn btn-primary top-delete-btn">Delete All Songs</div>

  <form onSubmit="submitSong(); return false">
    <input type="text" id="new-song" placeholder="Add a Song">
  </form>

  <p id="error-msg"></p>
</div>
</div>

<div class="songs whitebox">
<ul id="songlist">
<% @songs.each do |song| %>
<li class='songs' id="<%= song.id %>">
  <div onclick="deleteSong(<%= song.id %>)" class="btn btn-danger">Delete</div>
   <%= song.name %></li>
<% end %>
</ul>


</div>

app/views/songs/show.html.erb
<h1>show</h1>